Document: jellyfish
Title: Debian jellyfish Manual
Author: <insert document author here>
Abstract: This manual describes what jellyfish is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/jellyfish/jellyfish.sgml.gz

Format: postscript
Files: /usr/share/doc/jellyfish/jellyfish.ps.gz

Format: text
Files: /usr/share/doc/jellyfish/jellyfish.text.gz

Format: HTML
Index: /usr/share/doc/jellyfish/html/index.html
Files: /usr/share/doc/jellyfish/html/*.html
